services:
  - type: web
    name: efir-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: PORT
        value: 5001
      - key: CLIENT_URL
        value: http://localhost:3000
      - key: JWT_SECRET
        value: your-long-jwt-secret
    

  - type: web
    name: efir-admin
    env: node
    rootDir: admin
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_BACKEND_PORT
        value: 5002
      - key: JWT_SECRET
        value: your-admin-jwt-secret
      - key: ADMIN_EMAIL_DOMAIN
        value: government.gov.in
      - key: MONGO_URI
        value: your-mongodb-uri
   

  - type: web
    name: efir-citizen
    env: static
    rootDir: E-FIR
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: http://localhost:5001/api
    
